### ISSUE TITLE
Whitelist is enabled, and attempted to retrieve data from http://www.w3.org/TR/xhtml11/DTD/xhtml-datatypes-1.mod

### ISSUE THREAD

**Issue by vmassol** [css4j/xml-dtd#8]
Hi Carlos,

I'm trying to use DefaultEntityResolver with the following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<p>hello</p>
```

And I'm getting the error `Whitelist is enabled, and attempted to retrieve data from http://www.w3.org/TR/xhtml11/DTD/xhtml-datatypes-1.mod`.

I see that the local `xhtml-datatypes-1.mod` file is only registered for `http://www.w3.org/MarkUp/DTD/xhtml-datatypes-1.mod` but not for `http://www.w3.org/TR/xhtml11/DTD/xhtml-datatypes-1.mod`. Is that normal/expected?

Thanks

**Comment by carlosame** [comment]
Good catch, it is a bug in W3C's `xhtml11.dtd`. There, every XHTML 1.1 module is referenced by an absolute System ID except `xhtml-datatypes-1.mod` which is relative.

The URL `http://www.w3.org/TR/xhtml11/DTD/xhtml-datatypes-1.mod` does not exist and is not a valid supported System ID.

**Comment by vmassol** [comment]
Cool thanks.

BTW I've noticed that there are difference between these 3 files that we provide in XWiki and the ones you provide:
* https://github.com/xwiki/xwiki-commons/blob/cf0d01209716bd3864a90f42a2467b1526fee8e9/xwiki-commons-core/xwiki-commons-xml/src/main/resources/xhtml1-strict.dtd
* https://github.com/xwiki/xwiki-commons/blob/538fe33872fc6a3b66052bf82a0c6012501497f6/xwiki-commons-core/xwiki-commons-xml/src/main/resources/xhtml1-transitional.dtd

The diff:

```
diff --git a/xwiki-commons-core/xwiki-commons-xml/src/main/resources/xhtml-special.ent b/xwiki-commons-core/xwiki-commons-xml/src/main/resources/xhtml-special.ent
index dfb450b51..ca358b2fe 100644
--- a/xwiki-commons-core/xwiki-commons-xml/src/main/resources/xhtml-special.ent
+++ b/xwiki-commons-core/xwiki-commons-xml/src/main/resources/xhtml-special.ent
@@ -26,7 +26,7 @@
 <!ENTITY amp     "&#38;#38;"> <!--  ampersand, U+0026 ISOnum -->
 <!ENTITY lt      "&#38;#60;"> <!--  less-than sign, U+003C ISOnum -->
 <!ENTITY gt      "&#62;"> <!--  greater-than sign, U+003E ISOnum -->
-<!ENTITY apos     "&#39;"> <!--  apostrophe = APL quote, U+0027 ISOnum -->
+<!ENTITY apos   "&#39;"> <!--  apostrophe = APL quote, U+0027 ISOnum -->
 
 <!-- Latin Extended-A -->
 <!ENTITY OElig   "&#338;"> <!--  latin capital ligature OE,
diff --git a/xwiki-commons-core/xwiki-commons-xml/src/main/resources/xhtml1-strict.dtd b/xwiki-commons-core/xwiki-commons-xml/src/main/resources/xhtml1-strict.dtd
index f38f3086d..0e40613eb 100644
--- a/xwiki-commons-core/xwiki-commons-xml/src/main/resources/xhtml1-strict.dtd
+++ b/xwiki-commons-core/xwiki-commons-xml/src/main/resources/xhtml1-strict.dtd
@@ -16,27 +16,16 @@
    PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    SYSTEM "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"
 
-   $Revision: 570 $
-   $Date: 2005-05-29 21:05:56 +0200 (Sun, 29 May 2005) $
+   $Revision: 1.1 $
+   $Date: 2002/08/01 13:56:03 $
 
 -->
 
 <!--================ Character mnemonic entities =========================-->
 
-<!ENTITY % HTMLlat1 PUBLIC
-   "-//W3C//ENTITIES Latin 1 for XHTML//EN"
-   "xhtml-lat1.ent">
-%HTMLlat1;
-
-<!ENTITY % HTMLsymbol PUBLIC
-   "-//W3C//ENTITIES Symbols for XHTML//EN"
-   "xhtml-symbol.ent">
-%HTMLsymbol;
-
-<!ENTITY % HTMLspecial PUBLIC
-   "-//W3C//ENTITIES Special for XHTML//EN"
-   "xhtml-special.ent">
-%HTMLspecial;
+<!ENTITY % HTML5 SYSTEM
+   "https://www.w3.org/TR/html5/entities.dtd">
+%HTML5;
 
 <!--================== Imported Names ====================================-->
 
diff --git a/xwiki-commons-core/xwiki-commons-xml/src/main/resources/xhtml1-transitional.dtd b/xwiki-commons-core/xwiki-commons-xml/src/main/resources/xhtml1-transitional.dtd
index e79b94c85..aa0570165 100644
--- a/xwiki-commons-core/xwiki-commons-xml/src/main/resources/xhtml1-transitional.dtd
+++ b/xwiki-commons-core/xwiki-commons-xml/src/main/resources/xhtml1-transitional.dtd
@@ -23,20 +23,9 @@
 
 <!--================ Character mnemonic entities =========================-->
 
-<!ENTITY % HTMLlat1 PUBLIC
-   "-//W3C//ENTITIES Latin 1 for XHTML//EN"
-   "xhtml-lat1.ent">
-%HTMLlat1;
-
-<!ENTITY % HTMLsymbol PUBLIC
-   "-//W3C//ENTITIES Symbols for XHTML//EN"
-   "xhtml-symbol.ent">
-%HTMLsymbol;
-
-<!ENTITY % HTMLspecial PUBLIC
-   "-//W3C//ENTITIES Special for XHTML//EN"
-   "xhtml-special.ent">
-%HTMLspecial;
+<!ENTITY % HTML5 SYSTEM
+   "https://www.w3.org/TR/html5/entities.dtd">
+%HTML5;
 
 <!--================== Imported Names ====================================-->
 
@@ -196,9 +185,9 @@
 
 <!ENTITY % special.extra
    "object | applet | img | map | iframe">
-
+       
 <!ENTITY % special.basic
-   "br | span | bdo">
+       "br | span | bdo">
 
 <!ENTITY % special
    "%special.basic; | %special.extra;">
@@ -253,7 +242,7 @@
 
 <!ENTITY % pre.content
    "(#PCDATA | a | %special.basic; | %fontstyle.basic; | %phrase.basic; |
-       %inline.forms; | %misc.inline;)*">
+          %inline.forms; | %misc.inline;)*">
 
 <!-- form uses %Flow; excluding form -->
```

Any idea who's right? :)

**Comment by carlosame** [comment]
> Note that there are 4 files having a relative declaration

I know, there are quite a few fixes of this kind that I'm working at.

**Comment by vmassol** [comment]
Found another problem. You're providing `xhtml11-model-1.mod` but at https://github.com/css4j/xml-dtd/blob/master/src/io/sf/carte/doc/xml/dtd/DefaultEntityResolver.java#L132 you're writing `xhtml-11-model-1.mod`! :)

**Comment by carlosame** [comment]
Yes all those problems are now fixed. But I'm trying to update the DTDs and the funny thing is that if I get xmñ11.dtd from the official place http://www.w3.org/MarkUp/DTD/xhtml11.dtd I get this date:

```xml
Revision:   $Id: xhtml11.dtd,v 1.30 2009/06/24 17:24:55 ahby Exp $
```

But if I get it from the legacy https://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd I get the newer:
```xml
Revision:   $Id: xhtml11.dtd,v 1.1 2018/03/20 05:54:52 plehegar Exp $
```
Sigh.

**Comment by vmassol** [comment]
@carlosame thanks for fixing this so quickly. Just retested your changes in the context of XWiki and my example now works fine.

**Comment by vmassol** [comment]
@carlosame if you want to check what I've pushed (and verify I didn't make any licensing mistake), it's at https://github.com/xwiki/xwiki-commons/commit/fd20a6df981e68410a8a32f25118b2688e279f03 Thx!

**Comment by carlosame** [comment]
> @carlosame if you want to check what I've pushed (and verify I didn't make any licensing mistake), it's at [xwiki/xwiki-commons@fd20a6d](https://github.com/xwiki/xwiki-commons/commit/fd20a6df981e68410a8a32f25118b2688e279f03) Thx!

There are a few issues from the licensing point of view:

1) My Java files are under a BSD 3-clause license, however you put the header of a GNU Lesser General Public License. But the license that you get from a software project cannot be changed unless it is MIT-like (which is not the case). To make things easier, I hereby license the Java code under the GNU LGPL and GPL licenses, in addition to the initial BSD license.

2) You left unchanged the BSD-3-Clause `SPDX-License-Identifier` header:

https://github.com/xwiki/xwiki-commons/blob/fd20a6df981e68410a8a32f25118b2688e279f03/xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/AgentUtil.java#L25

however you are using a LGPL license. I'd suggest removing that line which is intended for use by automated tools.

3) The files under the `w3c` directory have been copied or **adapted** from the W3C and go by their own license. When this project was part of css4j, I had this declared in a LICENSES.txt file, but when I split xml-dtd out I forgot to carry the declaration. I have now added here a `NOTICE.txt` file with that information. You do not really need to do the same in XWiki, although you may want to create a NOTICE file which points out that not all of the files in XWiki Commons are under the LGPL (see the next point).

4) Apparently, all of the XWiki source files [begin with a header](https://github.com/xwiki/xwiki-commons/blob/fd20a6df981e68410a8a32f25118b2688e279f03/xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/internal/AgentUtil.java#L2-L3) that starts with this:

```
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
```
But then there is no NOTICE file in your repository. This is confusing, IMHO either there should be a NOTICE file or that paragraph should be removed.

The NOTICE file should specify:

- A copyrigt notice with an explanation about the copyright holders of the code. Anything related to copyright ownership (as promised by the aforementioned header).

- A reference to `LICENSE` as being the main license file, with an explanation about other licenses that only apply to some files.

Tomorrow I may file an issue in XWiki about the absence of the NOTICE file, unless you have a better idea.

**Comment by vmassol** [comment]
> Tomorrow I may file an issue in XWiki about the absence of the NOTICE file, unless you have a better idea.

About this point, we generate the NOTICE file (it's generated by Maven).

**Comment by carlosame** [comment]
> About this point, we generate the NOTICE file (it's generated by Maven) and include it into all the files we distribute.

I downloaded one of the XWiki commons jar files, I see that it says "Copyright 2004-2022 XWiki" and then proceeds to list what seems to be a number of dependencies which are probably being bundled in a fat jar? (otherwise, if they are just dependencies I do not see the point).

Would the NOTICE file include a reference to my files and the W3C files (due to the copyright not belonging to XWiki)?

We'll continue with this tomorrow.

**Comment by vmassol** [comment]
See https://github.com/xwiki/xwiki-commons/commit/8287e26bade6a9b4a598ffae241b269daf9dad34 and https://github.com/xwiki/xwiki-commons/commit/b22e7763903eaacf1b98cb5abf970eec04263fc4
